window.esdocSearchIndex = [
  [
    "touchonadmin/pages/util/errors/errors.js~customerror",
    "class/pages/util/errors/errors.js~CustomError.html",
    "<span>CustomError</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/errors/errors.js</span>",
    "class"
  ],
  [
    "touchonadmin/pages/util/db.js~db_setup",
    "class/pages/util/db.js~DB_Setup.html",
    "<span>DB_Setup</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/db.js</span>",
    "class"
  ],
  [
    "touchonadmin/pages/util/dbops.js~db_operations",
    "class/pages/util/dbops.js~DB_operations.html",
    "<span>DB_operations</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/dbops.js</span>",
    "class"
  ],
  [
    "touchonadmin/pages/util/util.js~phonenumbervalidate",
    "function/index.html#static-function-PhoneNumberValidate",
    "<span>PhoneNumberValidate</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/util.js</span>",
    "function"
  ],
  [
    "touchonadmin/pages/util/errors/errors.js~propertyrequirederror",
    "class/pages/util/errors/errors.js~PropertyRequiredError.html",
    "<span>PropertyRequiredError</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/errors/errors.js</span>",
    "class"
  ],
  [
    "touchonadmin/pages/util/util.js~b64decodeunicode",
    "function/index.html#static-function-b64DecodeUnicode",
    "<span>b64DecodeUnicode</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/util.js</span>",
    "function"
  ],
  [
    "touchonadmin/pages/util/util.js~checkpassword",
    "function/index.html#static-function-checkPassword",
    "<span>checkPassword</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/util.js</span>",
    "function"
  ],
  [
    "touchonadmin/pages/util/db.js~db_setup",
    "variable/index.html#static-variable-dB_Setup",
    "<span>dB_Setup</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/db.js</span>",
    "variable"
  ],
  [
    "touchonadmin/pages/util/util.js~formatphonenumber",
    "function/index.html#static-function-formatPhoneNumber",
    "<span>formatPhoneNumber</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/util.js</span>",
    "function"
  ],
  [
    "touchonadmin/pages/util/util.js~getindexofattrinobj",
    "function/index.html#static-function-getIndexOfAttrInObj",
    "<span>getIndexOfAttrInObj</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/util.js</span>",
    "function"
  ],
  [
    "touchonadmin/pages/util/util.js~mergeobjs",
    "function/index.html#static-function-mergeObjs",
    "<span>mergeObjs</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/util.js</span>",
    "function"
  ],
  [
    "touchonadmin/pages/util/util.js~removekey",
    "function/index.html#static-function-removeKey",
    "<span>removeKey</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/util.js</span>",
    "function"
  ],
  [
    "touchonadmin/pages/util/util.js~validateemail",
    "function/index.html#static-function-validateEmail",
    "<span>validateEmail</span> <span class=\"search-result-import-path\">touchonadmin/pages/util/util.js</span>",
    "function"
  ],
  [
    "pages/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "pages/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "pages/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "pages/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "pages/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "pages/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "pages/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "pages/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "pages/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "pages/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "pages/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "pages/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "pages/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "pages/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "pages/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "pages/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "pages/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "pages/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "pages/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "pages/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "pages/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "pages/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "pages/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "pages/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "pages/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "pages/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "pages/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "pages/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "pages/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "pages/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "pages/.external-ecmascript.js~String",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "pages/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "pages/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "pages/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "pages/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "pages/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "pages/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "pages/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "pages/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "pages/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "pages/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "pages/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "pages/.external-ecmascript.js~function",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "pages/.external-ecmascript.js~null",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "pages/.external-ecmascript.js~number",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "pages/.external-ecmascript.js~object",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "pages/.external-ecmascript.js~string",
    "external"
  ],
  [
    "pages/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "pages/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "pages/util/config.js",
    "file/pages/util/config.js.html",
    "pages/util/config.js",
    "file"
  ],
  [
    "pages/util/db.js",
    "file/pages/util/db.js.html",
    "pages/util/db.js",
    "file"
  ],
  [
    "pages/util/db.js~db_setup#_isdebug",
    "class/pages/util/db.js~DB_Setup.html#instance-member-_isDebug",
    "pages/util/db.js~DB_Setup#_isDebug",
    "member"
  ],
  [
    "pages/util/db.js~db_setup#constructor",
    "class/pages/util/db.js~DB_Setup.html#instance-constructor-constructor",
    "pages/util/db.js~DB_Setup#constructor",
    "method"
  ],
  [
    "pages/util/db.js~db_setup#getisdevorprod",
    "class/pages/util/db.js~DB_Setup.html#instance-method-getIsDevOrProd",
    "pages/util/db.js~DB_Setup#getIsDevOrProd",
    "method"
  ],
  [
    "pages/util/db.js~db_setup#log",
    "class/pages/util/db.js~DB_Setup.html#instance-method-log",
    "pages/util/db.js~DB_Setup#log",
    "method"
  ],
  [
    "pages/util/dbops.js",
    "file/pages/util/dbops.js.html",
    "pages/util/dbops.js",
    "file"
  ],
  [
    "pages/util/dbops.js~db_operations#adduser",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-addUser",
    "pages/util/dbops.js~DB_operations#addUser",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#constructor",
    "class/pages/util/dbops.js~DB_operations.html#instance-constructor-constructor",
    "pages/util/dbops.js~DB_operations#constructor",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#create_user",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-create_user",
    "pages/util/dbops.js~DB_operations#create_user",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#db",
    "class/pages/util/dbops.js~DB_operations.html#instance-member-db",
    "pages/util/dbops.js~DB_operations#db",
    "member"
  ],
  [
    "pages/util/dbops.js~db_operations#disableuser",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-disableUser",
    "pages/util/dbops.js~DB_operations#disableUser",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#error",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-error",
    "pages/util/dbops.js~DB_operations#error",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#getdata",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-getData",
    "pages/util/dbops.js~DB_operations#getData",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#getdatawithkey",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-getDataWithKey",
    "pages/util/dbops.js~DB_operations#getDataWithKey",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#get_current_user",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-get_current_user",
    "pages/util/dbops.js~DB_operations#get_current_user",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#get_user_info",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-get_user_info",
    "pages/util/dbops.js~DB_operations#get_user_info",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#get_user_token",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-get_user_token",
    "pages/util/dbops.js~DB_operations#get_user_token",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#get_user_type",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-get_user_type",
    "pages/util/dbops.js~DB_operations#get_user_type",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#listen_user_events",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-listen_user_events",
    "pages/util/dbops.js~DB_operations#listen_user_events",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#log",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-log",
    "pages/util/dbops.js~DB_operations#log",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#query",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-query",
    "pages/util/dbops.js~DB_operations#query",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#redirect",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-redirect",
    "pages/util/dbops.js~DB_operations#redirect",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#save_data",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-save_data",
    "pages/util/dbops.js~DB_operations#save_data",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#sign_in",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-sign_in",
    "pages/util/dbops.js~DB_operations#sign_in",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#sign_out",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-sign_out",
    "pages/util/dbops.js~DB_operations#sign_out",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#success",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-success",
    "pages/util/dbops.js~DB_operations#success",
    "method"
  ],
  [
    "pages/util/dbops.js~db_operations#uploadstudents",
    "class/pages/util/dbops.js~DB_operations.html#instance-method-uploadStudents",
    "pages/util/dbops.js~DB_operations#uploadStudents",
    "method"
  ],
  [
    "pages/util/errors/errors.js",
    "file/pages/util/errors/errors.js.html",
    "pages/util/errors/errors.js",
    "file"
  ],
  [
    "pages/util/errors/errors.js~customerror#constructor",
    "class/pages/util/errors/errors.js~CustomError.html#instance-constructor-constructor",
    "pages/util/errors/errors.js~CustomError#constructor",
    "method"
  ],
  [
    "pages/util/errors/errors.js~customerror#name",
    "class/pages/util/errors/errors.js~CustomError.html#instance-member-name",
    "pages/util/errors/errors.js~CustomError#name",
    "member"
  ],
  [
    "pages/util/errors/errors.js~propertyrequirederror#constructor",
    "class/pages/util/errors/errors.js~PropertyRequiredError.html#instance-constructor-constructor",
    "pages/util/errors/errors.js~PropertyRequiredError#constructor",
    "method"
  ],
  [
    "pages/util/errors/errors.js~propertyrequirederror#property",
    "class/pages/util/errors/errors.js~PropertyRequiredError.html#instance-member-property",
    "pages/util/errors/errors.js~PropertyRequiredError#property",
    "member"
  ],
  [
    "pages/util/util.js",
    "file/pages/util/util.js.html",
    "pages/util/util.js",
    "file"
  ]
]